name: CI - Bases

on:
  push:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: List
      uses: ./.github/actions/my-action
