name: CI - Bases

on:
  push:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    
    - name: Install package
      run: |
        chmod +x script.sh
        ./script.sh
