name: CI - Bases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Inicializando
      run: echo "Hola mundo. Bienvenido!"

    - name: Touch File
      run: touch file-test.txt

    - name: Write on File
      run: echo "Hola mundo" >> file-test.txt

    - name: Read File
      run: cat file-test.txt

  other-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    
    - name: List filesystem
      run: ls -la